### ISSUE TITLE
sbitx crash when grids.txt doesn't exist

### ISSUE THREAD

**Issue by mml** [drexjj/sbitx#101]
We don't check the return value of `fopen()` here in `hist_disp.c`.  In my case the crash occurred because I was in the wrong directory.

```
 35 void hd_createGridList() {
 36    onfFout = fopen("./web/grids.txt", "wb");
 37
 38     logbook_open();
 39     logbook_get_grids(addGridToFile);
 40
 41         fwrite("\0\0", 1, 2, onfFout);
 42         if (onfFout != NULL) fclose(onfFout);
 43 }
```

Also we can remove the "b" from `fopen` flags.

>  The  mode  string  can  also  include the letter 'b' either as a last character or as a character between the
>  characters in any of the two-character strings described above.  This is strictly for compatibility with  ISO
>  C and has no effect; the 'b' is ignored on all POSIX conforming systems, including Linux.

**Comment by drexjj** [comment]
added to v4.12 thanks
