### ISSUE TITLE
Everybody has the same ssh host keys

### ISSUE THREAD

**Issue by mml** [drexjj/sbitx#103]
Because we're all burning the exact same image of an already-setup system, it seems everybody has the exact same ssh host keys.  This probably isn't a huge security issue, but it is a minor detail it'd be nice to correct.  Probably best corrected by creating a re-usable image using tooling like [pi-gen](https://github.com/RPi-Distro/pi-gen) ([tutorial](https://opensource.com/article/21/7/custom-raspberry-pi-image)).

**Comment by drexjj** [comment]
Added sshkeygen binary and source code to generate new keys as needed.
