### ISSUE TITLE
Installation with Balena Etcher

### ISSUE THREAD

**Issue by W9MDO** [drexjj/sbitx#2]
First, I LOVE your work here!

No biggie, but I've had to use Raspberry Pi Imager to write my microsd cards. For some reason Etcher (updated version) always fails as it is finishing, but Imager seems to do well. I'm running Windows 11 and Trend Micro protection. 

If you like, I can recreate it, and take lots of screenshots. 

73,
Chuck W9MDO

**Comment by Mashintime** [comment]
I experienced issues with etcher as well.  If I used the uncompressed image it worked fine.

**Comment by drexjj** [comment]
Thank you for reporting this. I've updated the wiki with alternate instructions. https://github.com/drexjj/sbitx/wiki/Installing-a-Raspberry-Pi-image
