### ISSUE TITLE
FT8 mode fixes for better operation

### ISSUE THREAD

**Issue by MolKa51** [drexjj/sbitx#73]
With FT8, we can only CQ in the first/third period, there is no way to change this. Option to switch between even and odd periods. Also, the RX-pitch (green line) at FT8 would jump to the QSO frequency, indicating that the QSO partner is here, as in other digital applications, although this is only a cosmetic patch. The TX-pitch frequency can be set from the window, the disadvantage of this is that it is difficult to move it when the QSO partner is at the other end of the audio track and not answer, because it only answers on its own frequency. With FT8, the Sidetone window is unnecessary, because it is also available from the Menu, this space can be used for other things. 
Gyula HA3HZ

**Comment by drexjj** [comment]
"With FT8, we can only CQ in the first/third period, there is no way to change this."  It can be changed with the TX1ST button. Turn it on to respond at 00 and 30; turn it off to respond at 14 and 45.

**Comment by drexjj** [comment]
"The TX-pitch frequency can be set from the window, the disadvantage of this is that it is difficult to move it when the QSO partner is at the other end of the audio track and not answer, because it only answers on its own frequency. "

This should be moved to a separate issue.

**Comment by drexjj** [comment]
"The RX-pitch (green line) at FT8 would jump to the QSO frequency, indicating that the QSO partner is here, as in other digital applications, although this is only a cosmetic patch."

This should be moved to a separate issue.
