### ISSUE TITLE
Moving FT8 TX-pitch in a different way

### ISSUE THREAD

**Issue by MolKa51** [drexjj/sbitx#74]
The TX-pitch frequency can be set from the window, the disadvantage of this is that it is difficult to move it when the QSO partner is at the other end of the audio track and not answer, because it only answers on its own frequency. 
A tx2rx switch puts the transmit frequency at the same place as the receive frequency.

**Comment by drexjj** [comment]
> A tx2rx switch puts the transmit frequency at the same place as the receive frequency.

Please explain what tx2rx switch is and is it available somewhere that we can use?

**Comment by MolKa51** [comment]
Re: [drexjj/sbitx] Moving FT8 TX-pitch in a different way (Issue #74)



Hello jj,

The thing that exists in jtdx is that the receive and transmit frequencies are used separately on different frequencies or on the same frequency.
I think the smartest solution would be that when selecting the station, the green line indicating the reception frequency jumps to reception. 
It would be visible where that station is in the lane. The transmission frequency (red line) can be moved to a clear frequency with the right mouse button. 
There is not enough space on the display, so the button for setting reception and transmission to the same frequency could be, for example, the left mouse button. Fldigi, for example, uses the left mouse button when I select the receiving station and will transmit there.

Wednesday, October 16, 2024, 7:35:46 PM, you wrote:





A tx2rx switch puts the transmit frequency at the same place as the receive frequency.
Please explain what tx2rx switch is and is it available somewhere that we can use?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>




-- 
Best regards,
Molnar Gyula

**Comment by drexjj** [comment]
Closing this request. It is a JTDX problem which we are not in the business of fixing.
