### ISSUE TITLE
Add attenuator

### ISSUE THREAD

**Issue by MolKa51** [drexjj/sbitx#77]
On the lower bands 80M-40M it is sometimes necessary to use an Attenuator for reception. I'm thinking of a 10dB, 20dB level reduction, but I don't know if this can be done through software. I know the hardware implementation.

**Comment by Mashintime** [comment]
Not an expert, but I'd belive this would have to HW fix as software only comes into play later.  

If lowering IF Gain doesn't help I don't think there's anything we can do in software to help.

**Comment by MolKa51** [comment]
Re: [drexjj/sbitx] Add attenuator (Issue #77)



Hello Mashintime,

I had a hunch that this could not be solved with software. 
There is not enough space to insert an attenuator at the input of the receiver and to switch it on and off. 
The 80-60-40M is necessary for the input attenuation, especially during the winter propagation.

Wednesday, October 2, 2024, 10:42:23 PM, you wrote:





Not an expert, but I'd belive this would have to HW fix as software only comes into play later.
If lowering IF Gain doesn't help I don't think there's anything we can do in software to help.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>




-- 
Best regards,
Molnar Gyula

**Comment by SigmazGFX** [comment]
Might need to look into a less performant antenna system. (hi-hi)

**Comment by MolKa51** [comment]
Re: [drexjj/sbitx] Add attenuator (Issue #77)



Hello SigmazGFX,

Yes, a Dummy load would also be enough, it can also be tuned to 1:1.0, although it does not broadcast effectively anywhere.

Thursday, October 3, 2024, 7:02:20 PM, you wrote:





Might need to look into a less performant antenna system. (hi-hi)
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>




-- 
Best regards,
Molnar Gyula
